replicaCount: 1

image:
  repository: 256057170649.dkr.ecr.us-east-1.amazonaws.com/python-app
  tag: 1f109fb
  pullPolicy: IfNotPresent   # since we imported manually into kind

imagePullSecrets:
  - name: ecr-secret
service:
  type: ClusterIP
  port: 5000
  targetPort: 5000
containerPort: 5000
serviceAccount:
  create: false

httpRoute:
  enabled: false

autoscaling:
  enabled: false

ingress:
  enabled: true