apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app.fullname" . }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      {{- if .Values.nodePort -}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}


  selector:
    {{- include "python-app.selectorLabels" . | nindent 4 }}
